using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace JoySys.Builder
{
    internal class CreateCIFile
    {

        public static void GenerateRecipeFunction(IEnumerable<string> fieldNames, string outputFilePath)
        {
            if (fieldNames == null || !fieldNames.Any())
                throw new ArgumentException("Field names are required", nameof(fieldNames));

            var distinctFields = fieldNames.Distinct(StringComparer.OrdinalIgnoreCase).ToList();

            var sb = new StringBuilder();

            sb.AppendLine("//***************************************");
            sb.AppendLine("//***  Warning: Auto-generated file   ***");
            sb.AppendLine("//***  Do NOT edit this file manually ***");
            sb.AppendLine("//***************************************");
            sb.AppendLine();




            sb.AppendLine("STRING FUNCTION GetValidVal(STRING Field)");
            sb.AppendLine("	SELECT CASE Field");

            foreach (var fieldName in distinctFields)
            {
                sb.AppendLine($"		CASE \"{fieldName}\"");
                sb.AppendLine($"			RETURN ValidVal_{fieldName}();");
            }

            sb.AppendLine("		CASE ELSE"); 
            sb.AppendLine("\t\t\tMessage(\"GetValidVal \" ,\"GetValidVal Error \" + \" ^n Unknown field:\"+ Field, 16);\r\n\t\t\tRETURN \"\";");
            sb.AppendLine("	END SELECT");
            sb.AppendLine("END");
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine();


            sb.AppendLine(" INT FUNCTION VerifyVal(STRING tag,INT PhaseNum,STRING value,STRING tagType,STRING recName)");
            sb.AppendLine("	SELECT CASE tag");

            foreach (var fieldName in distinctFields)
            {
                sb.AppendLine($"		CASE \"{fieldName}\"");
                sb.AppendLine($"			RETURN Verify_{fieldName}(tag,PhaseNum,value,tagType,recName);");
            }

            sb.AppendLine("		CASE ELSE");
            sb.AppendLine("\t\t\tMessage(\"VerifyVal\" ,\"VerifyVal Error \" + \" ^n Unknown tag:\"+ tag, 16);\r\n\t\t\tRETURN -1;");
            sb.AppendLine("	END SELECT");
            sb.AppendLine("END");
            sb.AppendLine();

            //foreach (var fieldName in distinctFields)
            //{
            //    sb.AppendLine($"FUNCTION {fieldName}()");
            //    sb.AppendLine("	STRING strVal = \"1,2,3,4,5,6,7\";");
            //    sb.AppendLine("	RETURN strVal;");
            //    sb.AppendLine("END");
            //    sb.AppendLine();
            //}

            string directoryPath = Path.GetDirectoryName(outputFilePath);
            if (!string.IsNullOrEmpty(directoryPath))
            {
                Directory.CreateDirectory(directoryPath);
            }
            File.WriteAllText(outputFilePath, sb.ToString());



        }

        public static void AppendMissingFunctions_ValidVal(IEnumerable<string> distinctFields, string functionsFilePath)
        {
            var existingFunctions = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            bool isNewFile = false;

            if (File.Exists(functionsFilePath))
            {
                var fileContent = File.ReadAllText(functionsFilePath);

                var regex = new Regex(@"STRING FUNCTION\s+ValidVal_(\w+)\s*\(.*?\)", RegexOptions.IgnoreCase);

                var matches = regex.Matches(fileContent);

                foreach (Match match in matches)
                {
                    if (match.Success && match.Groups.Count > 1)
                    {
                        existingFunctions.Add(match.Groups[1].Value);
                    }
                }
            }
            else
            {
                string directoryPath = Path.GetDirectoryName(functionsFilePath);
                if (!string.IsNullOrEmpty(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }

                isNewFile = true;
            }

            var sb = new StringBuilder();

            if (isNewFile)
            {
                sb.AppendLine("//************************************************************");
                sb.AppendLine("//*  This file contains auto-generated functions             *");
                sb.AppendLine("//*  Please fill in each function with the                   *");
                sb.AppendLine("//*  appropriate return values.                              *");
                sb.AppendLine();
                sb.AppendLine("//*  These values will appear in dropdown menus              *");
                sb.AppendLine("//*  (ComboBoxes) for the end users.                         *");
                sb.AppendLine();
                sb.AppendLine("//*  Example:                                                *");
                sb.AppendLine("//*      FUNCTION rec_MyTag()                                *");
                sb.AppendLine("//*          STRING strVal = \"Option1,Option2,Option3\";      *");
                sb.AppendLine("//*          RETURN strVal;                                  *");
                sb.AppendLine("//*      END                                                 *");
                sb.AppendLine();
                sb.AppendLine("//*  Do NOT remove or rename any function.                   *");
                sb.AppendLine("//*  Only modify the return values as needed.                *");
                sb.AppendLine("//************************************************************");
                sb.AppendLine();

                sb.AppendLine();
            }

            foreach (var fieldName in distinctFields)
            {
                if (!existingFunctions.Contains(fieldName))
                {
                    sb.AppendLine($"STRING FUNCTION ValidVal_{fieldName}()");
                    sb.AppendLine("    STRING strVal = \"1,2,3,4,5\";//ADD VAL FOR COMBO");
                    sb.AppendLine("    RETURN strVal;");
                    sb.AppendLine("END");
                    sb.AppendLine();
                }
            }


            if (sb.Length > 0)
            {
                try
                {
                    if (isNewFile)
                    {
                        File.WriteAllText(functionsFilePath, sb.ToString());
                    }
                    else
                    {
                        File.AppendAllText(functionsFilePath, sb.ToString());
                    }
                }
                catch (IOException ioEx)
                {
                    Console.WriteLine($"I/O error while writing to file: {ioEx.Message}");
                }
                catch (UnauthorizedAccessException uaEx)
                {
                    Console.WriteLine($"Access denied when writing to file: {uaEx.Message}");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Unexpected error while appending functions: {ex.Message}");
                }
            }
        }


        /////
       
        public static void AppendMissingFunctions_Verify(IEnumerable<string> distinctFields, string functionsFilePath)
        {
            var existingFunctions = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            bool isNewFile = false;

            if (File.Exists(functionsFilePath))
            {
                var fileContent = File.ReadAllText(functionsFilePath);

                var regex = new Regex(@"INT FUNCTION\s+Verify_(\w+)\s*\(.*?\)", RegexOptions.IgnoreCase);

                var matches = regex.Matches(fileContent);

                foreach (Match match in matches)
                {
                    if (match.Success && match.Groups.Count > 1)
                    {
                        existingFunctions.Add(match.Groups[1].Value);
                    }
                }
            }
            else
            {
                string directoryPath = Path.GetDirectoryName(functionsFilePath);
                if (!string.IsNullOrEmpty(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }

                isNewFile = true;
            }

            var sb = new StringBuilder();

            if (isNewFile)
            {
                sb.AppendLine("//********************************************************************************");
                sb.AppendLine("//*  This file contains auto-generated validation functions                      *");
                sb.AppendLine("//*  Each function is responsible for verifying and saving                       *");
                sb.AppendLine("//*  recipe values entered by the end user.                                      *");
                sb.AppendLine("//*                                                                              *");
                sb.AppendLine("//*  These functions are called during recipe editing or                         *");
                sb.AppendLine("//*  execution, to validate and optionally store values.                         *");
                sb.AppendLine("//*                                                                              *");
                sb.AppendLine("//*  Function signature:                                                         *");
                sb.AppendLine("//*      INT FUNCTION Verify_rec_<TagName>(                                      *");
                sb.AppendLine("//*          STRING RName,                                                       *");
                sb.AppendLine("//*          INT PhaseNum,                                                       *");
                sb.AppendLine("//*          STRING tag,                                                         *");
                sb.AppendLine("//*          STRING value)                                                       *");
                sb.AppendLine("//*                                                                              *");
                sb.AppendLine("//*  Return value:                                                               *");
                sb.AppendLine("//*      1   = valid input, value was stored                                     *");
                sb.AppendLine("//*     -1   = invalid input, value was rejected                                 *");
                sb.AppendLine("//*                                                                              *");
                sb.AppendLine("//*  Example:                                                                    *");
                sb.AppendLine("//*      INT FUNCTION Verify_rec_RegisterX(RName, PhaseNum, tag, value)       *");
                sb.AppendLine("//*          IF StrTrim(value) = \"\" THEN                                         *");
                sb.AppendLine("//*              RETURN -1; // Invalid: empty input                              *");
                sb.AppendLine("//*          ELSE                                                                *");
                sb.AppendLine("//*              Recipe_UpsertTagValue(RName, tag, value,                        *");
                sb.AppendLine("//*                  \"<Description>\",                                           *");
                sb.AppendLine("//*                  IntToStr(PhaseNum + 1), 1);                                 *");
                sb.AppendLine("//*              RETURN 1; // Valid and saved                                   *");
                sb.AppendLine("//*          END                                                                 *");
                sb.AppendLine("//*      END                                                                     *");
                sb.AppendLine("//*                                                                              *");
                sb.AppendLine("//*  Do NOT remove or rename any function.                                       *");
                sb.AppendLine("//*  Only edit the logic inside each function body.                              *");
                sb.AppendLine("//********************************************************************************");


                sb.AppendLine();

                sb.AppendLine();
            }

            foreach (var fieldName in distinctFields)
            {
                if (!existingFunctions.Contains(fieldName))
                {
                    sb.AppendLine($"\r\nINT FUNCTION Verify_{fieldName}(STRING tag,INT PhaseNum,STRING value,STRING tagType,STRING recName)");
                    sb.AppendLine("    IF StrTrim(value) = \"\" THEN ");
                    sb.AppendLine("     RETURN - 1; //ERROR");
                    sb.AppendLine("    END");
                    sb.AppendLine("     Recipe_UpsertTagValue(tagType,recName, tag, value, \"<Description>\", IntToStr(PhaseNum + 1), 1);");
                    sb.AppendLine("     RETURN 1; //OK ");
                    sb.AppendLine("END");
                    sb.AppendLine();

                }
            }


            if (sb.Length > 0)
            {
                try
                {
                    if (isNewFile)
                    {
                        File.WriteAllText(functionsFilePath, sb.ToString());
                    }
                    else
                    {
                        File.AppendAllText(functionsFilePath, sb.ToString());
                    }
                }
                catch (IOException ioEx)
                {
                    Console.WriteLine($"I/O error while writing to file: {ioEx.Message}");
                }
                catch (UnauthorizedAccessException uaEx)
                {
                    Console.WriteLine($"Access denied when writing to file: {uaEx.Message}");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Unexpected error while appending functions: {ex.Message}");
                }
            }
        }



    }
}
